name: Run unit tests

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - name: Install npm packages
      run: npm install
    - name: Run tests with CTRF annotations
      run: npm test
    - name: Produce coverage report
      run: npm run coverage
      if: always()
    - name: Publish CTRF annotations
      run: npx github-actions-ctrf ctrf/ctrf-report.json
      if: always()
    - name: Run Coveralls
      uses: coverallsapp/github-action@v2
      if: always()
    